# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    # force all unspecified python hooks to run python3
    python: python3
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
    - id: check-merge-conflict
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.48.0
  hooks:
    - id: terraform_fmt
    #- id: terraform_validate
    - id: terraform_docs
    - id: terraform_tflint
      exclude: ^ci/
      args:
        - '--args=--only=terraform_deprecated_interpolation'
        #- '--args=--only=terraform_deprecated_index'
        # - '--args=--only=terraform_unused_declarations'
        - '--args=--only=terraform_comment_syntax'
        - '--args=--only=terraform_documented_outputs'
        - '--args=--only=terraform_documented_variables'
        - '--args=--only=terraform_typed_variables'
        - '--args=--only=terraform_module_pinned_source'
        - '--args=--only=terraform_naming_convention'
        # - '--args=--only=terraform_required_version'
        # - '--args=--only=terraform_required_providers'
        # - '--args=--only=terraform_standard_module_structure'
        - '--args=--only=terraform_workspace_remote'
